import type { Subject, Question } from "@/app/page"

const questionsData: Record<Subject, Question[]> = {
  biology: [
    {
      id: 1,
      question: "Which of the following best describes the importance of biotechnology in modern society?",
      options: [
        "It has no significant impact on society.",
        "It helps in conservation efforts and sustainable development.",
        "It primarily focuses on entertainment industry advancements.",
        "It only benefits a select group of individuals.",
      ],
      correctAnswer: 1,
      explanation:
        "Biotechnology plays a crucial role in conservation efforts and sustainable development by providing solutions for food security, environmental protection, and healthcare advancements.",
    },
    {
      id: 2,
      question:
        "What is the process by which genetic information is passed from parent to offspring in a stable manner known as?",
      options: ["Mitosis", "Meiosis", "Heredity", "Mutation"],
      correctAnswer: 2,
      explanation:
        "Heredity refers to the passing of genetic information from parent to offspring, ensuring stable transmission of traits over generations.",
    },
    {
      id: 3,
      question: "Which of the following correctly describes the role of the nervous system in the human body?",
      options: [
        "Controls voluntary movements only",
        "Regulates hormonal balance",
        "Receives and processes sensory information",
        "Produces energy for cellular activities",
      ],
      correctAnswer: 2,
      explanation:
        "The nervous system receives and processes sensory information from the environment, allowing the body to respond to stimuli appropriately.",
    },
    {
      id: 4,
      question: "In which organelle does the process of photosynthesis primarily take place?",
      options: ["Nucleus", "Mitochondria", "Chloroplast", "Endoplasmic reticulum"],
      correctAnswer: 2,
      explanation:
        "Photosynthesis primarily occurs in chloroplasts, where chlorophyll absorbs light energy and converts it into chemical energy.",
    },
    {
      id: 5,
      question: "What is the primary cause of climate change?",
      options: [
        "Natural factors only",
        "Human activities and natural factors",
        "Volcanic eruptions",
        "Changes in Earth's orbit",
      ],
      correctAnswer: 1,
      explanation:
        "Climate change is primarily caused by human activities such as deforestation, burning fossil fuels, and industrial processes, along with natural factors.",
    },
    {
      id: 6,
      question: "Which of the following is NOT a mode of disease transmission?",
      options: ["Airborne", "Waterborne", "Vector-borne", "Contact with non-infected individuals"],
      correctAnswer: 3,
      explanation:
        "Contact with non-infected individuals does not contribute to disease transmission; it is not a recognized mode of transmission.",
    },
    {
      id: 7,
      question: "What is the main product of cellular respiration?",
      options: ["Glucose", "Oxygen", "Carbon dioxide", "ATP (adenosine triphosphate)"],
      correctAnswer: 3,
      explanation: "The main product of cellular respiration is ATP, which is the primary energy currency of cells.",
    },
    {
      id: 8,
      question:
        "Which of the following best describes the purpose of the United Nations Framework Convention on Climate Change (UNFCCC)?",
      options: [
        "To promote climate change denial",
        "To establish binding emission reduction targets",
        "To facilitate international cooperation on climate change issues",
        "To exploit natural resources for economic gain",
      ],
      correctAnswer: 2,
      explanation:
        "The UNFCCC aims to facilitate international cooperation on climate change issues, promote sustainable development, and mitigate greenhouse gas emissions.",
    },
    {
      id: 9,
      question: "What is the primary function of enzymes in biological systems?",
      options: [
        "To provide structural support to cells",
        "To transport molecules across cell membranes",
        "To catalyze chemical reactions",
        "To store genetic information",
      ],
      correctAnswer: 2,
      explanation:
        "Enzymes function as biological catalysts, speeding up chemical reactions within cells without being consumed in the process.",
    },
    {
      id: 10,
      question: "How do fungi primarily obtain nutrients?",
      options: [
        "Through photosynthesis",
        "By absorbing nutrients from their surroundings",
        "By capturing prey",
        "By performing chemosynthesis",
      ],
      correctAnswer: 1,
      explanation: "Fungi obtain nutrients by absorbing them from their surroundings through external digestion.",
    },
    {
      id: 11,
      question: "What is the basic unit of life?",
      options: ["Atom", "Cell", "Tissue", "Organ"],
      correctAnswer: 1,
      explanation: "The cell is the basic structural and functional unit of all living organisms.",
    },
    {
      id: 12,
      question: "Which organelle is responsible for photosynthesis in plants?",
      options: ["Mitochondria", "Nucleus", "Chloroplast", "Ribosome"],
      correctAnswer: 2,
      explanation: "Chloroplasts contain chlorophyll and are the sites where photosynthesis occurs in plant cells.",
    },
    {
      id: 13,
      question: "What is DNA?",
      options: ["A protein", "A carbohydrate", "A nucleic acid", "A lipid"],
      correctAnswer: 2,
      explanation: "DNA (Deoxyribonucleic acid) is a nucleic acid that carries genetic information.",
    },
    {
      id: 14,
      question: "Which blood type is considered the universal donor?",
      options: ["A", "B", "AB", "O"],
      correctAnswer: 3,
      explanation: "Type O blood can be donated to people with any blood type, making it the universal donor.",
    },
    {
      id: 15,
      question: "What is the process by which plants make their own food?",
      options: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"],
      correctAnswer: 1,
      explanation:
        "Photosynthesis is the process by which plants use sunlight, water, and carbon dioxide to produce glucose.",
    },
    {
      id: 16,
      question: "Which part of the brain controls balance and coordination?",
      options: ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"],
      correctAnswer: 1,
      explanation: "The cerebellum is responsible for maintaining balance, posture, and coordinating movement.",
    },
    {
      id: 17,
      question: "What is the largest organ in the human body?",
      options: ["Liver", "Brain", "Skin", "Lungs"],
      correctAnswer: 2,
      explanation: "The skin is the largest organ of the human body, covering the entire external surface.",
    },
    {
      id: 18,
      question: "Which gas do plants absorb from the atmosphere during photosynthesis?",
      options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
      correctAnswer: 2,
      explanation: "Plants absorb carbon dioxide from the atmosphere and use it in photosynthesis to produce glucose.",
    },
    {
      id: 19,
      question: "What is the function of red blood cells?",
      options: ["Fight infection", "Transport oxygen", "Clot blood", "Produce hormones"],
      correctAnswer: 1,
      explanation: "Red blood cells contain hemoglobin, which binds to oxygen and transports it throughout the body.",
    },
    {
      id: 20,
      question: "Which vitamin is produced when skin is exposed to sunlight?",
      options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
      correctAnswer: 3,
      explanation: "Vitamin D is synthesized in the skin when it is exposed to ultraviolet B radiation from sunlight.",
    },
  ],
  geography: [
    {
      id: 21,
      question: "The concept of geography encompasses:",
      options: [
        "Only the physical features of the Earth",
        "Only the human-made features of the Earth",
        "Both the physical and human-made features of the Earth",
        "None of the above",
      ],
      correctAnswer: 2,
      explanation:
        "Geography is the study of both physical features (landforms, climate, etc.) and human-made features (cities, cultures, etc.) of the Earth and their interactions.",
    },
    {
      id: 22,
      question: "What are the effects of climate change?",
      options: [
        "Rising sea levels",
        "More frequent extreme weather events",
        "Disruption of ecosystems",
        "All of the above",
      ],
      correctAnswer: 3,
      explanation:
        "Climate change leads to rising sea levels, more frequent extreme weather events (such as hurricanes and heatwaves), and disruption of ecosystems (including loss of biodiversity). Therefore, the correct answer is All of the above.",
    },
    {
      id: 23,
      question: "What are the pillars of the Climate Resilient Green Economy of Ethiopia?",
      options: [
        "Sustainable agriculture and forestry",
        "Renewable energy",
        "Water resource management",
        "All of the above",
      ],
      correctAnswer: 3,
      explanation:
        "The Climate Resilient Green Economy of Ethiopia focuses on sustainable agriculture and forestry, renewable energy, and water resource management as its pillars. Therefore, the correct answer is All of the above.",
    },
    {
      id: 24,
      question: "What is the relationship between population and socio-economic development?",
      options: [
        "Higher population always leads to higher socio-economic development",
        "Lower population always leads to higher socio-economic development",
        "Population growth can either positively or negatively impact socio-economic development depending on various factors",
        "There is no relationship between population and socio-economic development",
      ],
      correctAnswer: 2,
      explanation:
        "The relationship between population and socio-economic development is complex and can vary depending on factors such as education, healthcare, and economic policies. Therefore, the correct answer is Population growth can either positively or negatively impact socio-economic development depending on various factors.",
    },
    {
      id: 25,
      question: "What are some measures taken to curb population growth?",
      options: [
        "Family planning programs",
        "Education and empowerment of women",
        "Access to contraceptives",
        "All of the above",
      ],
      correctAnswer: 3,
      explanation:
        "Measures to curb population growth include family planning programs, education and empowerment of women, and access to contraceptives. Therefore, the correct answer is All of the above.",
    },
    {
      id: 26,
      question: "What are the major geological processes associated with plate tectonics?",
      options: [
        "Volcanism and earthquakes",
        "Erosion and weathering",
        "Sedimentation and deposition",
        "None of the above",
      ],
      correctAnswer: 0,
      explanation:
        "Plate tectonics involves the movement and interaction of Earth's lithospheric plates, resulting in processes such as volcanism and earthquakes. Therefore, the correct answer is Volcanism and earthquakes.",
    },
    {
      id: 27,
      question: "What are the basic concepts of climate change?",
      options: [
        "Changes in temperature and precipitation patterns",
        "Human-induced alterations to the Earth's climate system",
        "Long-term shifts in atmospheric conditions",
        "All of the above",
      ],
      correctAnswer: 3,
      explanation:
        "The basic concepts of climate change include changes in temperature and precipitation patterns, human-induced alterations to the Earth's climate system, and long-term shifts in atmospheric conditions. Therefore, the correct answer is All of the above.",
    },
    {
      id: 28,
      question: "What is the largest continent by area?",
      options: ["Africa", "North America", "Asia", "Europe"],
      correctAnswer: 2,
      explanation: "Asia is the largest continent, covering about 30% of Earth's total land area.",
    },
    {
      id: 29,
      question: "Which river is the longest in the world?",
      options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
      correctAnswer: 1,
      explanation: "The Nile River is generally considered the longest river in the world at approximately 6,650 km.",
    },
    {
      id: 30,
      question: "What is the capital of Australia?",
      options: ["Sydney", "Melbourne", "Canberra", "Perth"],
      correctAnswer: 2,
      explanation: "Canberra is the capital city of Australia, located in the Australian Capital Territory.",
    },
    {
      id: 31,
      question: "Which mountain range contains Mount Everest?",
      options: ["Andes", "Rocky Mountains", "Alps", "Himalayas"],
      correctAnswer: 3,
      explanation: "Mount Everest is located in the Himalayas on the border between Nepal and Tibet.",
    },
    {
      id: 32,
      question: "What is the smallest country in the world?",
      options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"],
      correctAnswer: 2,
      explanation: "Vatican City is the smallest country in the world with an area of just 0.17 square miles.",
    },
    {
      id: 33,
      question: "Which desert is the largest in the world?",
      options: ["Sahara", "Gobi", "Kalahari", "Antarctica"],
      correctAnswer: 3,
      explanation: "Antarctica is technically the largest desert in the world, being a cold desert.",
    },
    {
      id: 34,
      question: "The Suez Canal connects which two bodies of water?",
      options: [
        "Red Sea and Mediterranean",
        "Atlantic and Pacific",
        "Indian and Pacific",
        "Black Sea and Mediterranean",
      ],
      correctAnswer: 0,
      explanation:
        "The Suez Canal connects the Red Sea and the Mediterranean Sea, providing a shipping route between Europe and Asia.",
    },
    {
      id: 35,
      question: "Which country has the most time zones?",
      options: ["Russia", "United States", "China", "Canada"],
      correctAnswer: 0,
      explanation: "Russia spans 11 time zones, more than any other country in the world.",
    },
    {
      id: 36,
      question: "What is the deepest ocean trench?",
      options: ["Puerto Rico Trench", "Java Trench", "Mariana Trench", "Peru-Chile Trench"],
      correctAnswer: 2,
      explanation: "The Mariana Trench in the Pacific Ocean is the deepest known part of Earth's oceans.",
    },
    {
      id: 37,
      question: "Which African country is completely surrounded by South Africa?",
      options: ["Swaziland", "Lesotho", "Botswana", "Namibia"],
      correctAnswer: 1,
      explanation: "Lesotho is an enclave completely surrounded by South Africa.",
    },
    {
      id: 38,
      question: "What is the main cause of desertification?",
      options: [
        "Natural climate variations",
        "Human activities like overgrazing",
        "Volcanic activity",
        "Ocean currents",
      ],
      correctAnswer: 1,
      explanation:
        "Desertification is primarily caused by human activities such as overgrazing, deforestation, and poor agricultural practices.",
    },
    {
      id: 39,
      question: "Which line of latitude divides the Earth into Northern and Southern hemispheres?",
      options: ["Tropic of Cancer", "Tropic of Capricorn", "Equator", "Prime Meridian"],
      correctAnswer: 2,
      explanation: "The Equator (0° latitude) divides the Earth into Northern and Southern hemispheres.",
    },
    {
      id: 40,
      question: "What type of climate is characterized by hot, dry summers and mild, wet winters?",
      options: ["Tropical", "Mediterranean", "Continental", "Polar"],
      correctAnswer: 1,
      explanation:
        "Mediterranean climate is characterized by hot, dry summers and mild, wet winters, typical of regions around the Mediterranean Sea.",
    },
  ],
  chemistry: [
    {
      id: 41,
      question: "What is the chemical symbol for gold?",
      options: ["Go", "Gd", "Au", "Ag"],
      correctAnswer: 2,
      explanation: "Au comes from the Latin word 'aurum', meaning gold.",
    },
    {
      id: 42,
      question: "What is the pH of pure water?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 1,
      explanation: "Pure water has a pH of 7, which is considered neutral on the pH scale.",
    },
    {
      id: 43,
      question: "Which gas makes up approximately 78% of Earth's atmosphere?",
      options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
      correctAnswer: 2,
      explanation: "Nitrogen makes up about 78% of Earth's atmosphere, while oxygen makes up about 21%.",
    },
    {
      id: 44,
      question: "What is the atomic number of carbon?",
      options: ["4", "6", "8", "12"],
      correctAnswer: 1,
      explanation: "Carbon has an atomic number of 6, meaning it has 6 protons in its nucleus.",
    },
    {
      id: 45,
      question: "Which type of bond involves the sharing of electrons?",
      options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
      correctAnswer: 1,
      explanation: "Covalent bonds form when atoms share electrons to achieve stable electron configurations.",
    },
    {
      id: 46,
      question: "What is the most abundant element in the universe?",
      options: ["Helium", "Oxygen", "Carbon", "Hydrogen"],
      correctAnswer: 3,
      explanation: "Hydrogen is the most abundant element in the universe, making up about 75% of normal matter.",
    },
    {
      id: 47,
      question: "Which acid is found in vinegar?",
      options: ["Hydrochloric acid", "Sulfuric acid", "Acetic acid", "Nitric acid"],
      correctAnswer: 2,
      explanation: "Acetic acid (CH₃COOH) is the main component that gives vinegar its sour taste and smell.",
    },
    {
      id: 48,
      question: "What is the chemical formula for table salt?",
      options: ["NaCl", "KCl", "CaCl₂", "MgCl₂"],
      correctAnswer: 0,
      explanation: "Table salt is sodium chloride, with the chemical formula NaCl.",
    },
    {
      id: 49,
      question: "Which noble gas is most commonly found in the atmosphere?",
      options: ["Helium", "Neon", "Argon", "Krypton"],
      correctAnswer: 2,
      explanation: "Argon makes up about 0.93% of Earth's atmosphere, making it the most abundant noble gas.",
    },
    {
      id: 50,
      question: "What happens to the volume of a gas when temperature increases at constant pressure?",
      options: ["Decreases", "Increases", "Stays the same", "Becomes zero"],
      correctAnswer: 1,
      explanation:
        "According to Charles's Law, the volume of a gas increases proportionally with temperature at constant pressure.",
    },
    {
      id: 51,
      question: "What is the chemical formula for water?",
      options: ["H₂O", "CO₂", "NaCl", "CH₄"],
      correctAnswer: 0,
      explanation: "Water has the chemical formula H₂O, consisting of two hydrogen atoms and one oxygen atom.",
    },
    {
      id: 52,
      question: "Which element has the highest electronegativity?",
      options: ["Oxygen", "Nitrogen", "Fluorine", "Chlorine"],
      correctAnswer: 2,
      explanation: "Fluorine has the highest electronegativity value of 4.0 on the Pauling scale.",
    },
    {
      id: 53,
      question: "What is the process of a solid changing directly to a gas called?",
      options: ["Melting", "Evaporation", "Sublimation", "Condensation"],
      correctAnswer: 2,
      explanation:
        "Sublimation is the process where a solid changes directly to a gas without passing through the liquid phase.",
    },
    {
      id: 54,
      question: "Which law states that equal volumes of gases contain equal numbers of molecules?",
      options: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Gay-Lussac's Law"],
      correctAnswer: 2,
      explanation:
        "Avogadro's Law states that equal volumes of gases at the same temperature and pressure contain equal numbers of molecules.",
    },
    {
      id: 55,
      question: "What is the molar mass of carbon dioxide (CO₂)?",
      options: ["28 g/mol", "32 g/mol", "44 g/mol", "48 g/mol"],
      correctAnswer: 2,
      explanation: "The molar mass of CO₂ is 44 g/mol (12 g/mol for C + 2 × 16 g/mol for O).",
    },
    {
      id: 56,
      question: "Which type of reaction involves the combination of two or more substances?",
      options: ["Decomposition", "Synthesis", "Single replacement", "Double replacement"],
      correctAnswer: 1,
      explanation: "Synthesis reactions involve the combination of two or more substances to form a single product.",
    },
    {
      id: 57,
      question: "What is the electron configuration of sodium (Na)?",
      options: ["1s² 2s² 2p⁶ 3s¹", "1s² 2s² 2p⁶", "1s² 2s² 2p⁶ 3s²", "1s² 2s² 2p⁵"],
      correctAnswer: 0,
      explanation: "Sodium has 11 electrons, so its electron configuration is 1s² 2s² 2p⁶ 3s¹.",
    },
    {
      id: 58,
      question: "Which compound is known as laughing gas?",
      options: ["NO", "NO₂", "N₂O", "NH₃"],
      correctAnswer: 2,
      explanation: "Nitrous oxide (N₂O) is commonly known as laughing gas and is used as an anesthetic.",
    },
    {
      id: 59,
      question: "What is the oxidation state of oxygen in most compounds?",
      options: ["-1", "-2", "+1", "+2"],
      correctAnswer: 1,
      explanation: "Oxygen typically has an oxidation state of -2 in most compounds.",
    },
    {
      id: 60,
      question: "Which catalyst is commonly used in the Haber process?",
      options: ["Platinum", "Iron", "Nickel", "Copper"],
      correctAnswer: 1,
      explanation: "Iron is the catalyst commonly used in the Haber process for the synthesis of ammonia.",
    },
  ],
  physics: [
    {
      id: 61,
      question: "What is the speed of light in vacuum?",
      options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
      correctAnswer: 0,
      explanation:
        "The speed of light in vacuum is approximately 3 × 10⁸ meters per second, a fundamental constant in physics.",
    },
    {
      id: 62,
      question: "Which law states that force equals mass times acceleration?",
      options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Gravitation"],
      correctAnswer: 1,
      explanation: "Newton's Second Law states that F = ma, where force equals mass times acceleration.",
    },
    {
      id: 63,
      question: "What is the unit of electric current?",
      options: ["Volt", "Ohm", "Ampere", "Watt"],
      correctAnswer: 2,
      explanation: "The ampere (A) is the SI unit of electric current, measuring the flow of electric charge.",
    },
    {
      id: 64,
      question: "Which type of wave requires a medium to travel?",
      options: ["Light wave", "Radio wave", "Sound wave", "X-ray"],
      correctAnswer: 2,
      explanation: "Sound waves are mechanical waves that require a medium (like air, water, or solids) to propagate.",
    },
    {
      id: 65,
      question: "What is the acceleration due to gravity on Earth?",
      options: ["9.8 m/s²", "10.8 m/s²", "8.8 m/s²", "11.8 m/s²"],
      correctAnswer: 0,
      explanation:
        "The acceleration due to gravity on Earth is approximately 9.8 m/s² or 9.81 m/s² to be more precise.",
    },
    {
      id: 66,
      question: "Which particle has no electric charge?",
      options: ["Proton", "Electron", "Neutron", "Ion"],
      correctAnswer: 2,
      explanation: "Neutrons are electrically neutral particles found in the nucleus of atoms.",
    },
    {
      id: 67,
      question: "What is the relationship between wavelength and frequency?",
      options: ["Directly proportional", "Inversely proportional", "No relationship", "Exponentially related"],
      correctAnswer: 1,
      explanation:
        "Wavelength and frequency are inversely proportional: as frequency increases, wavelength decreases (λ = c/f).",
    },
    {
      id: 68,
      question: "Which law of thermodynamics states that energy cannot be created or destroyed?",
      options: ["Zeroth Law", "First Law", "Second Law", "Third Law"],
      correctAnswer: 1,
      explanation: "The First Law of Thermodynamics is the law of conservation of energy.",
    },
    {
      id: 69,
      question: "What is the SI unit of power?",
      options: ["Joule", "Newton", "Watt", "Pascal"],
      correctAnswer: 2,
      explanation: "The watt (W) is the SI unit of power, equal to one joule per second.",
    },
    {
      id: 70,
      question: "Which phenomenon explains why the sky appears blue?",
      options: ["Reflection", "Refraction", "Scattering", "Absorption"],
      correctAnswer: 2,
      explanation: "Rayleigh scattering of sunlight by molecules in the atmosphere makes the sky appear blue.",
    },
    {
      id: 71,
      question: "What is the formula for kinetic energy?",
      options: ["KE = mv", "KE = ½mv²", "KE = mv²", "KE = ½mv"],
      correctAnswer: 1,
      explanation: "Kinetic energy is given by KE = ½mv², where m is mass and v is velocity.",
    },
    {
      id: 72,
      question: "Which type of electromagnetic radiation has the highest frequency?",
      options: ["Radio waves", "Visible light", "X-rays", "Gamma rays"],
      correctAnswer: 3,
      explanation: "Gamma rays have the highest frequency and energy in the electromagnetic spectrum.",
    },
    {
      id: 73,
      question: "What is Ohm's Law?",
      options: ["V = IR", "P = IV", "F = ma", "E = mc²"],
      correctAnswer: 0,
      explanation: "Ohm's Law states that voltage (V) equals current (I) times resistance (R): V = IR.",
    },
    {
      id: 74,
      question: "Which principle explains how airplanes generate lift?",
      options: ["Archimedes' Principle", "Bernoulli's Principle", "Pascal's Principle", "Hooke's Law"],
      correctAnswer: 1,
      explanation:
        "Bernoulli's Principle explains how the pressure difference above and below an airplane wing generates lift.",
    },
    {
      id: 75,
      question: "What is the escape velocity from Earth?",
      options: ["7.9 km/s", "11.2 km/s", "15.5 km/s", "20.1 km/s"],
      correctAnswer: 1,
      explanation:
        "The escape velocity from Earth is approximately 11.2 km/s, the minimum speed needed to escape Earth's gravitational pull.",
    },
    {
      id: 76,
      question: "Which law describes the relationship between pressure and volume of a gas?",
      options: ["Boyle's Law", "Charles's Law", "Gay-Lussac's Law", "Avogadro's Law"],
      correctAnswer: 0,
      explanation:
        "Boyle's Law states that pressure and volume are inversely proportional at constant temperature: PV = constant.",
    },
    {
      id: 77,
      question: "What is the unit of magnetic field strength?",
      options: ["Tesla", "Weber", "Henry", "Gauss"],
      correctAnswer: 0,
      explanation: "The tesla (T) is the SI unit of magnetic field strength or magnetic flux density.",
    },
    {
      id: 78,
      question: "Which type of lens converges light rays?",
      options: ["Concave lens", "Convex lens", "Cylindrical lens", "Fresnel lens"],
      correctAnswer: 1,
      explanation: "A convex lens (converging lens) brings parallel light rays to a focus point.",
    },
    {
      id: 79,
      question: "What is the period of a pendulum dependent on?",
      options: ["Mass", "Length", "Amplitude", "Material"],
      correctAnswer: 1,
      explanation:
        "The period of a simple pendulum depends primarily on its length and the acceleration due to gravity.",
    },
    {
      id: 80,
      question: "Which conservation law is violated in radioactive decay?",
      options: ["Energy", "Momentum", "Mass number", "Electric charge"],
      correctAnswer: 2,
      explanation:
        "In radioactive decay, mass number may change, but energy, momentum, and electric charge are conserved.",
    },
  ],
  history: [
    {
      id: 81,
      question: "In which year did World War II end?",
      options: ["1944", "1945", "1946", "1947"],
      correctAnswer: 1,
      explanation: "World War II ended in 1945 with the surrender of Japan in September.",
    },
    {
      id: 82,
      question: "Who was the first President of the United States?",
      options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"],
      correctAnswer: 2,
      explanation: "George Washington served as the first President of the United States from 1789 to 1797.",
    },
    {
      id: 83,
      question: "Which ancient wonder of the world was located in Alexandria?",
      options: ["Hanging Gardens", "Lighthouse", "Colossus", "Mausoleum"],
      correctAnswer: 1,
      explanation:
        "The Lighthouse of Alexandria (Pharos of Alexandria) was one of the Seven Wonders of the Ancient World.",
    },
    {
      id: 84,
      question: "The Renaissance period began in which country?",
      options: ["France", "Germany", "Italy", "England"],
      correctAnswer: 2,
      explanation:
        "The Renaissance began in Italy during the 14th century, particularly in cities like Florence and Venice.",
    },
    {
      id: 85,
      question: "Who wrote the Communist Manifesto?",
      options: ["Vladimir Lenin", "Karl Marx", "Friedrich Engels", "Both Marx and Engels"],
      correctAnswer: 3,
      explanation: "The Communist Manifesto was written jointly by Karl Marx and Friedrich Engels in 1848.",
    },
    {
      id: 86,
      question: "Which empire was ruled by Julius Caesar?",
      options: ["Greek Empire", "Roman Empire", "Persian Empire", "Byzantine Empire"],
      correctAnswer: 1,
      explanation: "Julius Caesar was a Roman general and statesman who played a critical role in the Roman Republic.",
    },
    {
      id: 87,
      question: "The Berlin Wall fell in which year?",
      options: ["1987", "1988", "1989", "1990"],
      correctAnswer: 2,
      explanation: "The Berlin Wall fell on November 9, 1989, marking a significant moment in the end of the Cold War.",
    },
    {
      id: 88,
      question: "Which civilization built Machu Picchu?",
      options: ["Aztec", "Maya", "Inca", "Olmec"],
      correctAnswer: 2,
      explanation: "Machu Picchu was built by the Inca civilization in the 15th century in present-day Peru.",
    },
    {
      id: 89,
      question: "The French Revolution began in which year?",
      options: ["1789", "1790", "1791", "1792"],
      correctAnswer: 0,
      explanation: "The French Revolution began in 1789 with the storming of the Bastille on July 14.",
    },
    {
      id: 90,
      question: "Who was known as the 'Iron Lady'?",
      options: ["Queen Elizabeth II", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"],
      correctAnswer: 1,
      explanation: "Margaret Thatcher, the British Prime Minister from 1979-1990, was nicknamed the 'Iron Lady'.",
    },
    {
      id: 91,
      question: "The American Civil War lasted from which years?",
      options: ["1861-1865", "1860-1864", "1862-1866", "1859-1863"],
      correctAnswer: 0,
      explanation: "The American Civil War lasted from 1861 to 1865, ending with the surrender of Confederate forces.",
    },
    {
      id: 92,
      question: "Which Egyptian queen was known for her relationships with Julius Caesar and Mark Antony?",
      options: ["Nefertiti", "Hatshepsut", "Cleopatra", "Ankhesenamun"],
      correctAnswer: 2,
      explanation:
        "Cleopatra VII was the last pharaoh of Egypt, famous for her relationships with Julius Caesar and Mark Antony.",
    },
    {
      id: 93,
      question: "The Industrial Revolution began in which country?",
      options: ["France", "Germany", "United States", "Great Britain"],
      correctAnswer: 3,
      explanation: "The Industrial Revolution began in Great Britain in the late 18th century.",
    },
    {
      id: 94,
      question: "Which treaty ended World War I?",
      options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Vienna", "Treaty of Westphalia"],
      correctAnswer: 0,
      explanation:
        "The Treaty of Versailles, signed in 1919, officially ended World War I between Germany and the Allied Powers.",
    },
    {
      id: 95,
      question: "Who was the first person to circumnavigate the globe?",
      options: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook"],
      correctAnswer: 2,
      explanation:
        "Ferdinand Magellan led the first expedition to circumnavigate the globe, though he died before completing the journey.",
    },
    {
      id: 96,
      question: "The Cold War was primarily between which two superpowers?",
      options: ["USA and China", "USSR and China", "USA and USSR", "USA and Germany"],
      correctAnswer: 2,
      explanation: "The Cold War was a period of geopolitical tension between the United States and the Soviet Union.",
    },
    {
      id: 97,
      question: "Which ancient Greek philosopher taught Alexander the Great?",
      options: ["Socrates", "Plato", "Aristotle", "Pythagoras"],
      correctAnswer: 2,
      explanation: "Aristotle was the tutor of Alexander the Great and taught him philosophy, politics, and science.",
    },
    {
      id: 98,
      question: "The Magna Carta was signed in which year?",
      options: ["1215", "1225", "1205", "1235"],
      correctAnswer: 0,
      explanation: "The Magna Carta was signed in 1215, limiting the power of the English monarchy.",
    },
    {
      id: 99,
      question: "Which empire was known as the 'Land of the Rising Sun'?",
      options: ["Chinese Empire", "Korean Empire", "Japanese Empire", "Mongol Empire"],
      correctAnswer: 2,
      explanation:
        "Japan has been known as the 'Land of the Rising Sun' due to its position east of the Asian mainland.",
    },
    {
      id: 100,
      question: "The Black Death occurred during which century?",
      options: ["13th century", "14th century", "15th century", "16th century"],
      correctAnswer: 1,
      explanation:
        "The Black Death, a devastating plague, occurred in the 14th century (1347-1351) and killed millions in Europe.",
    },
  ],
  civics: [
    {
      id: 101,
      question: "How many branches of government are there in the United States?",
      options: ["Two", "Three", "Four", "Five"],
      correctAnswer: 1,
      explanation: "The U.S. government has three branches: Executive, Legislative, and Judicial.",
    },
    {
      id: 102,
      question: "What is the supreme law of the United States?",
      options: ["Declaration of Independence", "Constitution", "Bill of Rights", "Articles of Confederation"],
      correctAnswer: 1,
      explanation: "The Constitution is the supreme law of the United States.",
    },
    {
      id: 103,
      question: "How many amendments are there to the Constitution?",
      options: ["25", "26", "27", "28"],
      correctAnswer: 2,
      explanation: "There are currently 27 amendments to the U.S. Constitution.",
    },
    {
      id: 104,
      question: "What is the minimum age to be President of the United States?",
      options: ["30", "35", "40", "45"],
      correctAnswer: 1,
      explanation: "The Constitution requires the President to be at least 35 years old.",
    },
    {
      id: 105,
      question: "Which amendment gave women the right to vote?",
      options: ["18th", "19th", "20th", "21st"],
      correctAnswer: 1,
      explanation: "The 19th Amendment, ratified in 1920, gave women the right to vote.",
    },
    {
      id: 106,
      question: "How many senators does each state have?",
      options: ["One", "Two", "Three", "Depends on population"],
      correctAnswer: 1,
      explanation: "Each state has exactly two senators in the U.S. Senate, regardless of population.",
    },
    {
      id: 107,
      question: "What is the term length for a U.S. Representative?",
      options: ["2 years", "4 years", "6 years", "8 years"],
      correctAnswer: 0,
      explanation: "U.S. Representatives serve two-year terms.",
    },
    {
      id: 108,
      question: "Which court is the highest in the United States?",
      options: ["Federal Court", "District Court", "Appeals Court", "Supreme Court"],
      correctAnswer: 3,
      explanation: "The Supreme Court is the highest court in the United States.",
    },
    {
      id: 109,
      question: "What are the first 10 amendments called?",
      options: ["Articles of Confederation", "Bill of Rights", "Declaration of Rights", "Constitutional Amendments"],
      correctAnswer: 1,
      explanation: "The first 10 amendments to the Constitution are called the Bill of Rights.",
    },
    {
      id: 110,
      question: "Who is the Commander in Chief of the military?",
      options: ["Secretary of Defense", "Chairman of Joint Chiefs", "President", "Congress"],
      correctAnswer: 2,
      explanation: "The President serves as the Commander in Chief of the U.S. military.",
    },
    {
      id: 111,
      question: "What is the purpose of the Electoral College?",
      options: ["To educate voters", "To elect the President", "To count votes", "To register voters"],
      correctAnswer: 1,
      explanation:
        "The Electoral College is the system used to elect the President and Vice President of the United States.",
    },
    {
      id: 112,
      question: "Which principle of government means that no one is above the law?",
      options: ["Separation of powers", "Checks and balances", "Rule of law", "Federalism"],
      correctAnswer: 2,
      explanation:
        "The rule of law principle means that all people and institutions are subject to and accountable to law.",
    },
    {
      id: 113,
      question: "What is the minimum age to vote in federal elections?",
      options: ["16", "17", "18", "21"],
      correctAnswer: 2,
      explanation: "The 26th Amendment set the minimum voting age at 18 for all federal elections.",
    },
    {
      id: 114,
      question: "Which amendment protects freedom of speech?",
      options: ["First Amendment", "Second Amendment", "Fourth Amendment", "Fifth Amendment"],
      correctAnswer: 0,
      explanation: "The First Amendment protects freedom of speech, religion, press, assembly, and petition.",
    },
    {
      id: 115,
      question: "What is the term length for a U.S. Senator?",
      options: ["2 years", "4 years", "6 years", "8 years"],
      correctAnswer: 2,
      explanation: "U.S. Senators serve six-year terms.",
    },
    {
      id: 116,
      question: "Which branch of government interprets the laws?",
      options: ["Executive", "Legislative", "Judicial", "Administrative"],
      correctAnswer: 2,
      explanation: "The Judicial branch, headed by the Supreme Court, interprets the laws.",
    },
    {
      id: 117,
      question: "What is the maximum number of terms a President can serve?",
      options: ["One", "Two", "Three", "Unlimited"],
      correctAnswer: 1,
      explanation: "The 22nd Amendment limits Presidents to two terms in office.",
    },
    {
      id: 118,
      question: "Which document declared American independence from Britain?",
      options: ["Constitution", "Bill of Rights", "Declaration of Independence", "Articles of Confederation"],
      correctAnswer: 2,
      explanation:
        "The Declaration of Independence, adopted in 1776, declared American independence from British rule.",
    },
    {
      id: 119,
      question: "What is the process of removing a President from office called?",
      options: ["Recall", "Impeachment", "Censure", "Resignation"],
      correctAnswer: 1,
      explanation:
        "Impeachment is the constitutional process for removing a President from office for high crimes and misdemeanors.",
    },
    {
      id: 120,
      question: "Which level of government has the power to declare war?",
      options: ["State", "Local", "Federal", "County"],
      correctAnswer: 2,
      explanation: "Only the federal government, specifically Congress, has the constitutional power to declare war.",
    },
  ],
}

export function getQuestionsForSubject(subject: Subject): Question[] {
  return questionsData[subject] || []
}
